name: reviewdog old version 2
on: [pull_request]
jobs:
  biome:
    name: runner / Biome
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: mongolyy/reviewdog-action-biome@v1.8.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          reviewdog_flags: '-fail-on-error=true'
