name: reviewdog multi option
on: [pull_request]
jobs:
  biome:
    name: runner / Biome
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: mongolyy/reviewdog-action-biome@feature/add-fail-level-at-suggester
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_level: error
          fail_on_error: true
