name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    name: 👸 Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: 📦 Install dependencies
        run: bun install
      - uses: mongolyy/reviewdog-action-biome@v2
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
